other_config:
  device: -1
  output_dir: results/moons #"/raid/carta/cl_dpmm/MOONS" # 'results'
  seed: -1
scenario_config:
  class: benchmarks.NIMoons
  params:
    n_experiences: 5
    num_samples: 20000
    num_classes: 10
    noise: 0.05
feature_extractor_name: "identity"
training_config:
  n_epochs: 10
classifier_config:
  class: models.cd_imm.CD_IMM
  params:
    K: 50
    D: 2
    alphaDP: 10
    tau0: 0
    c0: 0.01
    n0: 4
    B0: 1
    is_diagonal: [False, True]
    variance_init_value: 20
    num_classes: 2
optimiser_config:
  class: torch.optim.SGD
  params:
    lr: 0.8