other_config:
  device: 0
  output_dir: '/raid/carta/cl_dpmm/'
  seed: 22
scenario_config:
  class: benchmarks.moons.NCMoons
  params:
    n_experiences: 5
    num_samples: 20000
    num_classes: 10
    noise: 0.05
feature_extractor_config:
  class: models.misc.FlattenInput
strategy_config:
  class: StreamingLDA
  params:
    train_mb_size: 256
    streaming_update_sigma: [True, False]
    input_size: 2

num_classes: 10