other_config:
  device: 0
  output_dir: '/raid/carta/cl_dpmm/MOONS'
  seed: 22
scenario_config:
  class: benchmarks.moons.NIMoons
  params:
    n_experiences: 5
    num_samples: 20000
    num_classes: 2
    noise: 0.05
feature_extractor_name: "identity"
strategy_config:
  class: StreamingLDA
  params:
    train_mb_size: 256
    streaming_update_sigma: [True, False]
    input_size: 2

num_classes: 2
