other_config:
  device: 0
  output_dir: '/raid/carta/cl_dpmm/CIFAR100'
  max_num_cpu: 60
scenario_config:
  class: benchmarks.cifar100.cifar100_superclasses
  params:
    num_experiences: 10
feature_extractor_name: "cifar10_resnet18"
autoencoder_name: "ff_vae"

model:
  h_dim: [100, 200, 300]
  fc_layers: [3, 4]
  fc_units: [100, 200, 300]
  z_dim: [25, 50, 100]
  input_size: 160

num_classes: 20
iters: 10000
batch_size: 64
eval_s: 200
is_grid_search: False

image_size: 32
num_channels: 3